// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duklcvhtxmfzaiihsytw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1a2xjdmh0eG1memFpaWhzeXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjkwMzQsImV4cCI6MjA3MDg0NTAzNH0.oEHt0AiOphQHv6G3zTuIsDGJQxVDzmeuAp9hjACxnQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});